---
- hosts: 
    - webserver
  vars:
    - domain_name: "devops.rebrain.srwx.net"
    - nginx_root_dir: "/var/www"
    - ssl_key_dir: "/etc/ssl/certs"
    - host_params:
      - hostname: "farstone"
        nbr: 1
    - package_names:
      - nginx
      - letsencrypt
      - git
    - letsencrypt_remaining_days: 15
    - nginx_sendfile_status: "on"
    - nginx_tcp_nopush_status: "on"
    - nginx_tcp_nodelay_status: "on"
    - nginx_max_connections: 40000

  roles:
#    - base
#    - packages
#    - www
    - letsencrypt
