---
- hosts: 
    - webserver

  vars:
    mem_size: 2048
    domain_name: "devops.rebrain.srwx.net"
    host_params:
      - hostname: "farstone-0"
        port: "8080"
      - hostname: "farstone-1"
        port: "8080"
      - hostname: "_"
        port: "80"

  tasks:
    - name: Installing nginx webserver on Debian
      apt:
        allow_unauthenticated: yes 
        name: nginx
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Installing nginx webserver on Centos
      yum:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Installing new nginx config
      vars:
        mem_size: "{{ ansible_facts['memtotal_mb'] }}"
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: reload_nginx

    - name: Removing default vhost config file
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: reload_nginx      

    - name: Installing vhost config
      template: 
        src: virtualhost.conf.j2
        dest: /etc/nginx/sites-available/{{ item.hostname }}.{{ domain_name }}.conf
        owner: root
        group: root
        mode: '0644'
      loop: "{{ host_params }}"
      notify: reload_nginx

    - name: Create a symbolic link to sites-enabled
      file:
        src: /etc/nginx/sites-available/{{ item.hostname }}.{{ domain_name }}.conf
        dest: /etc/nginx/sites-enabled/{{ item.hostname }}.{{ domain_name }}.conf
        owner: root
        group: root
        state: link
      loop: "{{ host_params }}"
      notify: reload_nginx

  handlers:
    - name: reload_nginx
      service:
        name: nginx
        state: reloaded 
