---
- hosts: 
    - webserver
  vars:
    domain_name: "devops.rebrain.srwx.net"

  roles:
    - base

    - role: packages
      vars:
        package_names:
          - nginx
          - letsencrypt

    - role: www
      vars:
        host_params:
          - hostname: "farstone"
            ports:
              - "80"
              - "443"
            nbr: 1
    - role: letsencrypt
      vars:
        - ssl_key_dir: "/etc/ssl"
