---
- hosts: 
    - webserver

  vars:
    mem_size: 2048

  tasks:
    - name: Installing nginx webserver on Debian
      apt:
        allow_unauthenticated: yes 
        name: nginx
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Installing nginx webserver on Centos
      yum:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Installing new nginx config
      vars:
        mem_size: "{{ ansible_facts['memtotal_mb'] }}"
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: reload_nginx

    - name: Remove default vhost config file
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: reload_nginx      

    - name: Installing first vhost config
      template: 
        src: virtualhost.conf.j2
        dest: /etc/nginx/sites-available/{{ ansible_facts['os_family'] }}_{{ item.hostname }}.devops.srwx.net.conf
        owner: root
        group: root
        mode: '0644'
      loop:
        - { hostname: 'host1', port: '80'}
        - { hostname: 'host2', port: '8080'}
      notify: reload_nginx

    - name: Create a symbolic link to sites-enabled
      file:
        src: /etc/nginx/sites-available/{{ ansible_facts['os_family'] }}_{{ item }}.devops.srwx.net.conf
        dest: /etc/nginx/sites-enabled/{{ ansible_facts['os_family'] }}_{{ item }}.devops.srwx.net.conf
        owner: root
        group: root
        state: link
      loop:
        - 'host1'
        - 'host2'
      notify: reload_nginx

  handlers:
    - name: reload_nginx
      service:
        name: nginx
        state: reloaded 
