---
- hosts: 
    - webserver
  tasks:
    - name: Installing nginx webserver
      apt:
        allow_unauthenticated: yes 
        name: nginx
        state: present

    - name: Installing new nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: reload_nginx

    - name: Remove default vhost config file
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: reload_nginx      

    - name: Installing first vhost config
      template: 
        src: virtualhost.conf.j2
        dest: /etc/nginx/sites-available/{{ item.hostname }}.devops.srwx.net.conf
        owner: root
        group: root
        mode: '0644'
      loop:
        - { hostname: 'farstone0', port: '80'}
        - { hostname: 'farstone1', port: '8080'}
      notify: reload_nginx

    - name: Create a symbolic link to sites-enabled
      file:
        src: /etc/nginx/sites-available/{{ item }}.devops.srwx.net.conf
        dest: /etc/nginx/sites-enabled/{{ item }}.devops.srwx.net.conf
        owner: root
        group: root
        state: link
      loop:
        - 'farstone0'
        - 'farstone1'
      notify: reload_nginx

  handlers:
    - name: reload_nginx
      service:
        name: nginx
        state: reloaded 
