---
- hosts: 
    - webserver

  roles:
    - base

    - role: packages
      vars:
        package_names:
          - nginx

    - role: www
      vars:
        domain_name: "devops.rebrain.srwx.net"
        host_params:
          - hostname: "farstone-0"
            port: "8080"
          - hostname: "farstone-1"
            port: "8080"
          - hostname: "_"
            port: "80"

