---
- hosts: 
    - webserver
  vars:
    - domain_name: "devops.rebrain.srwx.net"
    - nginx_root_dir: "/var/www"
    - ssl_key_dir: "/etc/ssl/certs"
    - host_params:
      - hostname: "farstone"
        nbr: 1
    - package_names:
      - nginx
      - letsencrypt
      - git
    - letsencrypt_remaining_days: 15

  roles:
  - base
  - packages
  - www
  - letsencrypt
