---
- name: Install packages (apt)
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ package_names }}"
  when: ansible_facts['os_family'] == 'Debian'
  tags: "common"

- name : Install packages (yum)
  yum:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ package_names }}"
  when: ansible_facts['os_family'] == 'RedHat'
  tags: "common"

- name: Install nginx (apt)
  apt:
    update_cache: yes
    name: "nginx"
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  tags: "nginx"

- name : Install nginx (yum)
  yum:
    update_cache: yes
    name: "nginx"
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
  tags: "common"

