---
- name: Install packages (apt)
  include_tasks: apt.yml
  when: ansible_facts['os_family'] == 'Debian'

- name : Install packages (yum)
  include_tasks: yum.yml
  when: ansible_facts['os_family'] == 'RedHat'

