---
- name: Install new nginx config
  vars:
    mem_size: "{{ ansible_facts['memtotal_mb'] }}"
  template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'
  notify: reload_nginx

- name: Remove default vhost config file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload_nginx

- name: Install vhost config
  template:
    src: virtualhost.conf.j2
    dest: /etc/nginx/sites-available/{{domain_name}}.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload_nginx

- name: Create a symbolic link to sites-enabled
  file:
    src: /etc/nginx/sites-available/{{ domain_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ domain_name }}.conf
    owner: root
    group: root
    state: link
  notify: reload_nginx

- name: Create folder for website
  file:
    path: "{{ nginx_root_dir }}/{{ item.hostname }}.{{ domain_name }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  loop: "{{ host_params }}"
