---
- name: Create ssl directory
  file:
    path: "{{ ssl_key_dir }}"
    mode: 0750
    state: directory

- name: Create ssl directory
  file:
    path: "{{ ssl_key_dir }}/{{ domain_name }}"
    mode: 0750
    state: directory

- name: Find account.key
  local_action:
    module: stat
    path: "/{{ ssl_key_dir }}/{{ domain_name }}/account.key"
  register: account_key

- name: Generate account.key
  local_action: shell openssl genrsa 4096 > "{{ ssl_key_dir }}/{{ domain_name }}/account.key"
  when: account_key.stat.exists == False

# generate domain key, if necessary
- name: Find domain.key
  local_action:
    module: stat
    path: "{{ letsencrypt_cert_dir }}/{{ domain }}/domain.key"
  register: domain_key
  become: no
  run_once: true


- name: Generate domain.key
  local_action: shell openssl genrsa 4096 > "{{ letsencrypt_cert_dir }}/{{ domain }}/domain.key"
  become: no
  run_once: true
  when: domain_key.stat.exists == False
