- name: Create users
  user:
    name: "{{ item.name | mandatory }}"
    comment: "{{ item.comment | mandatory }}"
    groups: "{{ item.groups | default([]) | join(',') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: "{{ item.state | default('present') }}"
    remove: "{{ item.remove | default('no') }}"
    password: "*NP*"
  with_items:
    - "{{ users }}"
  no_log: True

- name: Add keys to users
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1.key | mandatory}}"
    state: "{{ item.1.state | default('present') }}"
  with_subelements:
    - "{{ users }}"
    - ssh_keys
  no_log: True

- name: Create SSH keys folder
  file:
    path: "/home/{{ item.name }}/.ssh/domain.key" 
    state: directory
    mode: 0700
  with_items:
    - "{{ users }}"
  no_log: True

- name: Push private key
  copy:
    src: "{{ playbook_dir }}/secretkey"
    dest: "/home/{{ item.name }}/.ssh/domain.key"
  with_items:
    - "{{ users }}"
  no_log: True
