---
- name: Install Python
  include_tasks: apt.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Python
  include_tasks: yum.yml
  when: ansible_facts['os_family'] == 'RedHat'


- name: Download get-pip.py
  get_url:
      url: 'https://bootstrap.pypa.io/get-pip.py'
      dest: /tmp/get-pip.py

- name: Install pip
  command: "python get-pip.py"
  args:
    chdir: /tmp
- name: Install pyOpenSSL
  pip:
    name: pyopenssl
