---
- name: Select Nginx user
  set_fact:
    nginx_user: "www-data"
  when: ansible_facts['os_family'] == 'Debian'

- name: Select Nginx user
  set_fact:
    nginx_user: "nginx"
  when: ansible_facts['os_family'] == 'RedHat'

- name: Create challenge directory
  file:
    path: "{{ nginx_root_dir }}/{{ fqdn }}/.well-known/acme-challenge"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0555
    state: directory
    
- name: Create ssl directory
  file:
    path: "{{ ssl_key_dir }}/{{ fqdn }}"
    mode: 0750
    state: directory

- name: Find account.key
  stat:
    path: "{{ ssl_key_dir }}/{{ fqdn }}/account.key"
  register: account_key

- name: Generate RSA 4096 account key
  openssl_privatekey:
    path: "{{ ssl_key_dir }}/{{ fqdn }}/account.key"
    type: RSA
    size: 4096

- name: Find domain.key
  stat:
    path: "{{ ssl_key_dir }}/{{ fqdn }}/domain.key"
  register: domain_key

- name: Generate RSA 4096 domain key
  openssl_privatekey:
    path: "{{ ssl_key_dir }}/{{ fqdn }}/domain.key"
    type: RSA
    size: 4096

- name: Find domain.csr
  stat:
    path: "{{ ssl_key_dir }}/{{ fqdn }}/domain.csr"
  register: domain_csr

- name: Create Certificate Signing Request
  openssl_csr:
    path: "{{ ssl_key_dir }}/{{ fqdn }}/domain.csr"
    privatekey_path: "{{ ssl_key_dir }}/{{ fqdn }}/domain.key"
    common_name: "{{ fqdn | join('')}}"

- name: Create a challenge for farstone.devops.rebrain.srwx.net
  acme_certificate:
    account_key_src: "{{ ssl_key_dir }}/{{ fqdn }}/account.key"
    csr: "{{ ssl_key_dir }}/{{ fqdn }}/domain.csr"
    dest: "{{ ssl_key_dir }}/{{ fqdn }}/devops.crt"
    fullchain_dest: "{{ ssl_key_dir }}/{{ fqdn }}/devops-fullchain.pem"
    chain_dest: "{{ ssl_key_dir }}/{{ fqdn }}/devops-chain.pem"
    account_email: "alex.farstone@gmail.com"
    acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
    acme_version: 2
    terms_agreed: "yes"
    challenge: "http-01"
    remaining_days: "{{ letsencrypt_remaining_days }}"
    modify_account: "yes"
  register: create_challenge
  tags: 
    - create-cert

- name: Copy challenge data
  copy:
    content: "{{ create_challenge.challenge_data[fqdn| join('')]['http-01']['resource_value'] }}"
    dest: "{{ nginx_root_dir }}/{{ fqdn }}/.well-known/acme-challenge/{{ create_challenge.challenge_data[fqdn | join('')]['http-01']['resource'] | basename }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0555
  register: challenge_ok
  tags: 
    - create-cert

- name: Create certificate
  acme_certificate:
    account_key_src: "{{ ssl_key_dir }}/{{ fqdn }}/account.key"
    csr: "{{ ssl_key_dir }}/{{ fqdn }}/domain.csr"
    dest: "{{ ssl_key_dir }}/{{ fqdn }}/signed.crt"
    fullchain_dest: "{{ ssl_key_dir }}/{{ fqdn }}/signed-fullchain.pem"
    chain_dest: "{{ ssl_key_dir }}/{{ fqdn }}/signed-chain.pem"
    account_email: "alex.farstone@gmail.com"
    acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
    acme_version: 2
    terms_agreed: "yes"
    challenge: "http-01"
    remaining_days: "{{ letsencrypt_remaining_days }}"
    modify_account: "yes"
    data: "{{ create_challenge }}"
  register: verify_challenge
  ignore_errors: yes
  tags: 
    - create-cert
