---
- name: Prepare hostnames variable
  set_fact:
    fqdn: "{{ (lookup('template', './hosts.j2').split(',')) | replace('\\n','')}}"
  #  set_fact:
  #    fqdn: "{{ lookup('template', './hosts.j2',wantlist=True) | replace('\n', '')}}"
  #  delegate_to: localhost
  #

- name: Update Letsencrypt
  git:
    repo: "https://github.com/letsencrypt/letsencrypt"
    dest: "/opt/letsencrypt"

- name: Create ssl directory
  file:
    path: "{{ ssl_key_dir }}"
    owner: root
    group: root
    mode: 0750
    state: directory

- name: Get Let'sEncrypt certificate for all domains
  include_tasks: get_cert.yml
  loop: "{{ fqdn }}"
