---
#- name: Prepare hostnames variable
#  set_fact:
#    fqdn: "{{ (lookup('template', './hosts.j2').split(',')) | replace('\\n','')}}"

- name: Update Letsencrypt
  git:
    repo: "https://github.com/letsencrypt/letsencrypt"
    dest: "/opt/letsencrypt"

- name: Create ssl directory
  file:
    path: "{{ ssl_key_dir }}"
    owner: root
    group: root
    mode: 0750
    state: directory

- name: Get Let'sEncrypt certificate for all domains
  include_tasks: get_cert.yml
  loop: "{{ fqdn }}"

- name: Install SSL vhost config
  template:
    src: virtualhost.conf.j2
    dest: /etc/nginx/sites-available/{{domain_name}}-SSL.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload_nginx

- name: Create a symbolic link to sites-enabled
  file:
    src: /etc/nginx/sites-available/{{ domain_name }}-SSL.conf
    dest: /etc/nginx/sites-enabled/{{ domain_name }}-SSL.conf
    owner: root
    group: root
    state: link
  notify: reload_nginx

